# Site settings
title: My GitHub Pages Site
description: A brief description of my site
url: https://yash0211.github.io
baseurl: "/Projects"

# Author information
author:
  name:
  email: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Theme settings
theme: jekyll-theme-slate
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
- jekyll-remote-theme

# Social media links (optional)
social:
  github: 
  linkedin: 

# Exclude files and directories from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

