# _config.yml

remote_theme: "mmistakes/minimal-mistakes" # Add the Minimal Mistakes theme
plugins:
  - jekyll-remote-theme # Required for the remote theme to work on GitHub Pages
  - jekyll-seo-tag
  - jekyll-feed

# Site settings
title: "Your Site Title"
description: "A description of your site."
baseurl: "Projects" # Leave empty unless your site is in a subdirectory
url: "https://yash0211.github.io" # Replace with your GitHub Pages URL

# Additional configuration for Minimal Mistakes (optional)
author:
  name: "Your Name"
  email: "you@example.com"

# Social Links
social:
  github: yourusername
  linkedin: your-linkedin-username

# Enable Google Analytics (optional)
google_analytics: "UA-XXXX-Y"

# Enable Disqus comments (optional)
disqus:
  shortname: "your-disqus-shortname"


